name: action cicd

on:
  push:
    branches: ["brnch_1"]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run command
        run: echo "run success"
